/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo;

/**
 *
 * @author kirito205
 */
public class Ejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
        PanelCliente.setVisible(false);
        PanelVisitante.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelQueEres = new javax.swing.JPanel();
        cmbSeleccion = new javax.swing.JComboBox<>();
        PanelCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        PanelVisitante = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnAceptarVisita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelQueEres.setBorder(javax.swing.BorderFactory.createTitledBorder("Que eres"));
        PanelQueEres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Visita" }));
        cmbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionActionPerformed(evt);
            }
        });
        PanelQueEres.add(cmbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 29, -1, -1));

        PanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        PanelCliente.setToolTipText("");
        PanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Clave Usuario");
        PanelCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 17, -1, -1));
        PanelCliente.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 38, 90, -1));

        jLabel2.setText("Contrasena");
        PanelCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 69, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        PanelCliente.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 121, 90, -1));
        PanelCliente.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        PanelVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder("Visitante"));
        PanelVisitante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre");
        PanelVisitante.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 17, -1, -1));
        PanelVisitante.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 38, 103, -1));

        jLabel4.setText("Edad");
        PanelVisitante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 69, -1, -1));
        PanelVisitante.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 90, 103, -1));

        btnAceptarVisita.setText("Aceptar");
        btnAceptarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarVisitaActionPerformed(evt);
            }
        });
        PanelVisitante.add(btnAceptarVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 121, 103, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelQueEres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelQueEres, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(PanelVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionActionPerformed
        // TODO add your handling code here:
        if (cmbSeleccion.getSelectedIndex()+1==1) {
           PanelCliente.setVisible(true);
           PanelVisitante.setVisible(false);
        }
        if (cmbSeleccion.getSelectedIndex()+1==2) {
            PanelCliente.setVisible(false);
            PanelVisitante.setVisible(true);
        }
    }//GEN-LAST:event_cmbSeleccionActionPerformed

    private void btnAceptarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarVisitaActionPerformed
        // TODO add your handling code here:
        String nombre="Nombre: "+txtNombre.getText();
        String edad="Edad: "+txtEdad.getText();
        datos(nombre,edad);
    }//GEN-LAST:event_btnAceptarVisitaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String nombre="Clave Usuario: "+txtClave.getText();
        String edad="Contrasena: "+txtContrasena.getText();
        datos(nombre,edad);
    }//GEN-LAST:event_btnAceptarActionPerformed

    public static void datos(String n,String b){
        Resultado z= new Resultado();
        z.lblUsuario.setText(n);
        z.lblContrasena.setText(b);
        z.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelQueEres;
    private javax.swing.JPanel PanelVisitante;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarVisita;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtClave;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
